views/calendar.py
from flask import Blueprint, render_template
from flask_login import login_required

calendar = Blueprint('calendar', __name__, template_folder='templates')

@calendar.route('/calendar')
@login_required
def calendar_page():
    return render_template('calendar.html', active_nav='calendar')

views/classes.py
from flask import Blueprint, render_template
from flask_login import login_required

classes = Blueprint('classes', __name__, template_folder='templates')

@classes.route('/classes')
@login_required
def classes_page():
    return render_template('classes.html', active_nav='classes')

views/dashboard.py
from flask import Blueprint, render_template, request, session
from flask_login import current_user, login_required

dashboard = Blueprint('dashboard', __name__, template_folder='templates')

@dashboard.route('/dashboard')
@login_required
def dashboard_page():
    # Check if the user is new via session
    if 'IS_NEW_USER' in session and session['IS_NEW_USER'] == 'True':
        # User is new, show new user dashboard
        return render_template('dashboard-new-user.html', active_nav='home')

    # Does the current user have complete linked accounts?
    incomplete_moodle = current_user.moodle_account.password == ''
    current_user_google = current_user.google_accounts
    incomplete_google = len(current_user_google.keys()) == 0

    # Check if we are returning from account linking process
    if 'link_type' in session:
        # User is returning from account linking process
        link_type = session['link_type']
        link_status = session['link_status']
        del session['link_type']
        del session['link_status']
        return render_template('dashboard.html',
                               active_nav='home',
                               link_type=link_type,
                               link_status=link_status,
                               incomplete_google=incomplete_google,
                               incomplete_moodle=incomplete_moodle)

    # User is returning, show normal dashboard
    return render_template('dashboard.html',
                           active_nav='home',
                           incomplete_google=incomplete_google,
                           incomplete_moodle=incomplete_moodle)

views/login.py
from flask import Blueprint, current_app, render_template, request, redirect, session, url_for
from flask_login import current_user, login_user
from google.auth.transport import requests
from google.oauth2 import id_token
from models.profile import create_from_google_jwt
from os import environ
from urllib.parse import urljoin, urlparse

login = Blueprint('login', __name__, template_folder='templates')


# https://stackoverflow.com/a/61446498
def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and \
           ref_url.netloc == test_url.netloc


@login.route('/login', methods=['GET'])
def login_page():
    # Make sure that required environment variables are set
    if 'DOMAIN' not in environ:
        raise RuntimeError('DOMAIN environment variable not set')
    if 'GOOGLE_CLIENT_ID' not in environ:
        raise RuntimeError('GOOGLE_CLIENT_ID environment variable not set')

    # Redirect to dashboard if already logged in
    if current_user.is_authenticated:
        return redirect(url_for('dashboard.dashboard_page'))

    return render_template(
        'login.html',
        full_width='true',
        domain=environ['DOMAIN'],
        google_client_id=environ['GOOGLE_CLIENT_ID']
    )


@login.route('/login', methods=['POST'])
def login_form():
    # If the POSTed form data has the "g_csrf_token" field,
    # then we assume the login was with a Google account
    # and the form data contains a JWT token we should verify.
    if 'g_csrf_token' not in request.form:
        # Form data does not contain the JWT token,
        # so something must have gone wrong. Abort login.
        return 'CSRF token missing', 400

    # First check if the CSRF token checks out...
    csrf_cookie = request.cookies.get('g_csrf_token')
    if not csrf_cookie:
        return 'CSRF cookie missing', 400
    if csrf_cookie != request.form['g_csrf_token']:
        return 'CSRF token mismatch', 400

    # ...then decode the JWT using Google's library
    try:
        id_info = id_token.verify_oauth2_token(
            request.form['credential'],
            requests.Request(),
            environ['GOOGLE_CLIENT_ID']
        )
    except Exception as e:
        # Could not decode JWT
        return f'Invalid JWT: {str(e)}', 400
    else:
        # Decoded JWT successfully.
        # Is the user verified?
        if not id_info['email_verified']:
            return 'Email not verified', 400

    # Does this user exist?
    email = id_info['email']
    db = current_app.config['DB']
    matching_user = db.lookup_user_by_email(email)
    is_new_user = matching_user is None
    if is_new_user:
        # Is the user verified?
        if not id_info['email_verified']:
            return 'Email not verified', 400

        # Create user
        matching_user = create_from_google_jwt(id_info)
        db.add_user(matching_user)

    # Log in
    login_user(matching_user)

    # Redirect to the next page
    session['IS_NEW_USER'] = str(is_new_user)
    next_url = request.args.get('next')
    if not is_safe_url(next_url):
        return 'Unsafe redirect URL', 400
    return redirect(next_url or url_for('index.index_page'))

views/logout.py
from flask import Blueprint, redirect, url_for
from flask_login import logout_user

logout = Blueprint('logout', __name__, template_folder='templates')

@logout.route('/logout')
def logout_page():
    logout_user()
    return redirect(url_for('index.index_page'))

views/settings.py
from flask import Blueprint, render_template, request
from flask_login import login_required

settings = Blueprint('settings', __name__, template_folder='templates')

@settings.route('/settings')
@login_required
def settings_page():
    return render_template('settings.html')

templates/base-auth.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/base-auth.css') }}">
{% endblock %}

{% block body %}
<div class="auth-page-root">
    <div class="auth-page-image">
        <img class="auth-page-logo" src="{{ url_for('static', filename='images/logo-2x.png') }}" alt="GoVL&#234;">
    </div>
    <div class="auth-page-form">
        <div class="auth-page-form-content">
            <div>{% block auth_content %}{% endblock %}</div>
        </div>
    </div>
</div>

<div id="g_id_onload" data-client_id="{{ google_client_id }}" data-login_uri="{{ domain }}/login"
    data-prompt_parent_id="g_id_onload" data-auto_prompt="true" data-context="signin" data-ux_mode="popup"
    data-auto_select="true">
</div>
{% endblock %}

templates/base-logged-in.html
{% extends "base.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/base-logged-in.css') }}">
{% block local_style %}{% endblock %}
{% endblock %}

{% block body %}
<nav class="px-3 navbar navbar-expand-lg navbar-light">
    <a class="mx-3 navbar-brand" href="{{ url_for('dashboard.dashboard_page') }}">
        <img src="{{ url_for('static', filename='images/logo-2x.png') }}" alt="GoVL&#234;">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-content" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-content">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if active_nav == 'home' %}active{% endif %}">
                <a class="nav-link" href="{{ url_for('dashboard.dashboard_page') }}">Home</a>
            </li>
            <li class="nav-item {% if active_nav == 'classes' %}active{% endif %}">
                <a class="nav-link" href="{{ url_for('classes.classes_page') }}">Classes</a>
            </li>
            <li class="nav-item {% if active_nav == 'calendar' %}active{% endif %}">
                <a class="nav-link" href="{{ url_for('calendar.calendar_page') }}">Calendar</a>
            </li>
            <li class="nav-item dropdown">
                <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false"></button>
                <div class="mr-5 dropdown-menu dropdown-menu-right text-right">
                    <a class="dropdown-item" href="{{ url_for('settings.settings_page') }}">Settings</a>
                    <a class="dropdown-item" href="https://github.com/govle-192-21-2/govle/#readme" rel="noopener" target="_blank">About GoVL&#234;</a>
                    <a class="dropdown-item" href="{{ url_for('logout.logout_page') }}">Log out</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

{% if full_width == 'true' %}
<div class="container-fluid mt-4">
{% else %}
<div class="container mt-4">
{% endif %}
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>GoVL&#234;{% block title %}{% endblock %}</title>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg" color="#20bf55') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    <meta name="apple-mobile-web-app-title" content="GoVL&ecirc;">
    <meta name="application-name" content="GoVL&ecirc;">
    <meta name="msapplication-TileColor" content="#20bf55">
    <meta name="msapplication-config" content="{{ url_for('static', filename='favicon/browserconfig.xml') }}">
    <meta name="theme-color" content="#ffffff">

    <!-- CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;500;700&display=swap">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <style type="text/css">
        * {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI",
                Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji",
                "Segoe UI Emoji", "Segoe UI Symbol";
        }
        h1, h2, h3, h4, h5, h6 { font-weight: 700 }
    </style>
    {% block head %}
    {% endblock %}
</head>

<body>
    <!-- Main content -->
    {% block body %}
    {% endblock %}

    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
        integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
        crossorigin="anonymous"></script>
    <script type="module"
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule
        src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

templates/calendar.html
{% extends "base-logged-in.html" %}

{% block title %}
&#8212; Calendar
{% endblock %}

{% block content %}
<!-- Put your code here -->

<html>
<style>
table {
  border-collapse: collapse;
  table-layout: fixed;
  width: 70%;
}

.flex-container {
    display: flex;
    align-items: center;
    justify-content: center;
}

.rectangle_red {
    width: 24px;
    height: 24px;
    top: 0px;
    position: relative;

    background: #C81A2F;
    border-radius: 6px;
}

.rectangle_green {
    width: 24px;
    height: 24px;
    top: 0px;
    position: relative;

    background: #199A44;
    border-radius: 6px;
}


body{
    font-family: 'Inter';
}
th {
  padding: 0px 0px 20px;
  text-align: center;
  border-bottom: 1px solid #ddd;
  color: #6D6D6D;
}

td {
  padding: 0px 0px 60px;
  border-bottom: 1px solid #ddd;
  word-wrap: break-word;
}

.calendar-numbers{
    font-weight: bold;
    text-align: center;
    padding-bottom: 5px;
}

h2, p {
  text-align: center;

}

.uvle-box {
    background-color: #C81A2F;
    border-radius: 5px;
    color: #ddd;
    font-style: normal;
    font-size: 10px;
    font-weight: 0;
    padding: 2.5px 2.5px 2.5px 2.5px;
    position: absolute;
    width: 110px;
}

.google-box {
    background-color: #199A44;
    border-radius: 5px;
    color: #ddd;
    font-style: normal;
    font-size: 12px;
    font-weight: 0;
    padding: 2.5px 2.5px 2.5px 2.5px;
    position: absolute;
    width: 110px;
}

.leftbutton:hover, .rightbutton:hover{
    color:#6D6D6D
}

.leftbutton:active, .rightbutton:active{
    color:#C81A2F
}
</style>
<body>
    <div class = 'flex-container'  style = "gap: 270px;">
        <span class = "leftbutton", style = "font-size: 35px", onclick="getPreviousMonth(days)">&#10094</span>
        <h2>
        </h2>
        <span class = "rightbutton", style = "font-size: 35px", onclick="getNextMonth(days)">&#10095</span>
    </div>
    <div class = 'flex-container', style = "gap: 10px; padding: 18px;">
        <div class = 'rectangle_red', style = "order: 1;"></div>
        <div style = "order: 1;">UVLe</div>
        <div class = 'rectangle_green', style = "order: 1;"></div>
        <div style = "order: 1;">Google Classroom</div>
    </div>
      
    <table align="center" 
        cellspacing="20" cellpadding="20">
        <thead>
            <tr>
                <th>SUN</th>
                <th>MON</th>
                <th>TUE</th>
                <th>WED</th>
                <th>THU</th>
                <th>FRI</th>
                <th>SAT</th>
            </tr>
        </thead>
          
        <tbody>
           
        </tbody>
    </table>
</body>
  
</html>
{% endblock %}

{% block scripts %}
<!-- The following JavaScript file will be at /static/scripts/calendar.js -->
<script src="{{ url_for('static', filename='scripts/calendar.js') }}"></script>
{% endblock %}

templates/classes.html
{% extends "base-logged-in.html" %}

{% block title %}
&#8212; Classes
{% endblock %}

{% block local_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/classes.css') }}">
{% endblock %}

{% block content %}
<!-- Header -->
<div class="row">
    <div class="col-md-12 mb-4">
        <h1 class="text-center">Your classes</h1>
    </div>
</div>

<!-- List of classes per platform -->
<div class="row my-4">
    <div class="col-md-12">
        <h2>UVL&#234;</h2>
    </div>
</div>
<div class="row pb-4" id="classes-moodle">
    <div class="col-md-12 text-center">
        <div class="spinner-border mx-auto text-primary" role="status">
            <span class="sr-only">Loading...</span>           
        </div>
    </div>
</div>
<hr class="pb-4">
<div class="row mb-4">
    <div class="col-md-12">
        <h2>Google Classroom</h2>
    </div>
</div>
<div class="row pb-4" id="classes-classroom">
    <div class="col-md-12 text-center">
        <div class="spinner-border mx-auto text-primary" role="status">
            <span class="sr-only">Loading...</span>           
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<!-- The following JavaScript file will be at /static/scripts/classes.js -->
<script src="{{ url_for('static', filename='scripts/classes.js') }}"></script>
{% endblock %}

templates/dashboard-new-user.html
{% extends "base-logged-in.html" %}

{% block title %}
&#8212; Home
{% endblock %}

{% block local_style %}
<style>
    #welcome-illustration {
        max-height: 400px;
    }

    @media (max-width: 768px) {
        #welcome-illustration {
            max-height: 200px;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="text-center">
            <img class="img-fluid mb-4" id="welcome-illustration"
                 src="{{ url_for('static', filename='images/welcome-illus.png') }}"
                 alt="Illustration">
            <h1 class="mx-auto">👋 Welcome to GoVL&#234;, {{ current_user['name'] }}</h1>
            <p class="mx-auto">Link your class accounts to get started.</p>
        </div>
    </div>
</div>
<div class="row justify-content-center my-3">
    <div class="col-6">
        <a class="btn btn-primary btn-block" href="{{ url_for('link-google.link_google_page') }}" role="button">Link Google Classroom ↗</a>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <a class="btn btn-primary btn-block" href="{{ url_for('link-moodle.link_moodle_page') }}" role="button">Link UVL&#234; ↗</a>
    </div>
</div>
{% endblock %}

templates/dashboard.html
{% extends "base-logged-in.html" %}

{% block title %}
&#8212; Home
{% endblock %}

{% block local_style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.12/css/weather-icons.min.css"
    integrity="sha512-r/Gan7PMSRovDus++vDS2Ayutc/cSdl268u047n4z+k7GYuR7Hiw71FsT3QQxdKJBVHYttOJ6IGLnlM9IoMToQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer">
<link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">
{% endblock %}

{% block content %}
{% if link_status != 'failure' %}
<div class="row">
    <div class="offset-xl-2 col-xl-4 col-12">
        <h1 id="greeting">Good <span id="time-of-day">day</span>,<br>{{ current_user['name'] }}</h1>
    </div>
    <div class="col-xl-4 col-12">
        <div class="weather">
            <div class="weather-icon">
                <i id="weather-icon" class="wi"></i>
            </div>
            <div class="weather-detail">
                <h2 id="weather-temp">Loading weather...</h2>
                <p id="weather-desc"></p>
                <p id="weather-fl"></p>
            </div>
        </div>
    </div>
</div>
{% endif %}

{# Account linking message #}
<div class="row justify-content-center">
    <div class="col-12 col-md-8">
{% if link_status == 'success' %}
        <div class="alert alert-success text-center">
            <strong>Success!</strong> Your
            {% if link_type == 'google' %}Google
            {% elif link_type == 'moodle' %}UVL&#234;
            {% endif %}
            account has been linked.
        </div>
{% elif link_status == 'failure' %}
        <div class="alert alert-danger text-center">
            <h4>There was an error linking your account</h4>
            <p class="mb-0">
            {% if link_type == 'google' %}
                Could not link your Google Classroom account. Please deauthorize GoVL&#234; under
                <strong>Third-party apps with account access</strong> at
                <a href="https://myaccount.google.com/permissions" target="_blank">Google My Account</a>
                before attempting to link again.
            {% elif link_type == 'moodle' %}
                Could not link your UVL&#234; account. Please check your username and password and try again.
            {% endif %}
            </p>
        </div>
{% endif %}
    </div>
</div>

{# Unlinked accounts message #}
{% if incomplete_moodle == True or incomplete_google == True %}
<div class="row justify-content-center">
    <div class="col-12 col-md-8">
        <h4>Link your class accounts</h4>
        <p>
            GoVL&#234; works best with all your accounts working together.<br>
            Please link your accounts to continue.
        </p>
        {% if incomplete_google == True %}
        <p>
            <a href="{{ url_for('link-google.link_google_page') }}"
               class="btn btn-primary">
                Link Google Classroom &#8599;
            </a>
        </p>
        {% else %}
        <div class="alert alert-success">
            <p>Google Classroom linked</p>
        </div>
        {% endif %}
        {% if incomplete_moodle == True %}
        <p>
            <a href="{{ url_for('link-moodle.link_moodle_page') }}"
               class="btn btn-primary">
                Link UVL&#234; &#8599;
            </a>
        </p>
        {% else %}
        <div class="alert alert-success">
            <p>UVL&#234; linked</p>
        </div>
        {% endif %}
        <hr class="my-5"/>
    </div>
</div>
{% endif %}

<div class="row justify-content-center">
    <div class="col-xl-8 col-12 text-center" id="deadlines-container">
        <div class="spinner-border mx-auto text-primary" role="status">
            <span class="sr-only">Loading...</span>           
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='scripts/dashboard.js') }}"></script>
{% endblock %}

templates/homepage.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='styles/homepage.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<nav class="px-3 navbar navbar-expand-lg navbar-light">
    <a class="ml-3 navbar-brand" href="{{ url_for('dashboard.dashboard_page') }}">
        <img src="{{ url_for('static', filename='images/logo-2x.png') }}"
            class="d-inline-block align-top mr-2"
            alt="GoVL&#234;">
        <strong>GoVL&#234;</strong>
    </a>
    <a class="ml-auto nav-link"
        href="https://github.com/govle-192-21-2/govle"
        rel="noopener" target="_blank">View on GitHub &nearr;</a>
</nav>

<div class="container-fluid mt-4">
    <div class="row text-center" id="hero">
        <div class="col">
            <div class="hero-img">
                <img class="mw-100"
                    src="{{ url_for('static', filename='images/meditating.svg') }}" alt="meditating">
            </div>
            <div class="hero-text mt-4">
                <h1>All your classes, in one place.</h1>
                <a href="{{ url_for('login.login_page') }}" role="button">Sign in or register &rarr;</a>
            </div>
        </div>
    </div>
    <div class="row" id="pitch">
        <div class="offset-lg-1 col-lg-4 col-12 text-center">
            <img class="mw-100 my-4"
                src="{{ url_for('static', filename='images/clumsy.svg') }}"
                alt="clumsy person with papers">
            <h3 class="my-4">Bringing platforms together...</h3>
            <p>
                GoVL&#234; was born out of a need to keep track of classes across different online learning platforms,
                brought about by the shift to remote learning during the pandemic.<br><br>
                With GoVL&#234;, you get a bird's-eye view of your classes from both Google Classroom and UVL&#234;,
                hence the name GoVL&#234;.
            </p>
        </div>
        <div class="offset-lg-2 col-lg-4 col-12 text-center">
            <img class="mw-100 my-4"
                src="{{ url_for('static', filename='images/unboxing.svg') }}"
                alt="unboxing">
            <h3 class="my-4">...privately and securely</h3>
            <p>
                We know how annoying it is to have yet another password to generate or remember,
                so we made it easy to log in to GoVL&#234;: just log in with your University of the Philippines
                Google account.<br><br>
                Your Google Classroom and UVL&#234; credentials are never stored in our database, and your UVL&#234;
                password is protected before transmission with 4,096-bit RSA encryption.
            </p>
        </div>
    </div>
    <div class="row align-items-center" id="opensource">
        <div class="col-lg-4 col-12">
            <h3>Open source,<br>powered by open-source</h3>
        </div>
        <div class="col-lg-4 col-12 text-center">
            <img class="mw-100"
                src="{{ url_for('static', filename='images/loving.svg') }}"
                alt="loving">
        </div>
        <div class="col-lg-4 col-12">
            <p>
                GoVL&#234; is completely open-source, and it cannot exist without other amazing open-source
                technologies.<br><br>
                The website is deployed directly and instantly from our GitHub repository, so you can be sure
                that updates are fast and authentic.
            </p>
        </div>
    </div>
    <div class="row text-center" id="footer">
        <div class="col">
            <img class="mb-4"
                src="{{ url_for('static', filename='images/logo.png') }}"
                alt="GoVL&#234;">
            <p class="mb-0"><strong>Made with &heartsuit; in 2022 by</strong></p>
            <p>Coleen Crisostomo, Jared Dantis, JC Peroz, Lee Monique Sadang</p>
            <p>Licensed under the MIT License</p>
            <p>Illustrations used under the CC0 license from <a class="text-light" href="https://www.opendoodles.com/">OpenDoodles</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block head %}
<link href="{{ url_for('static', filename='styles/index.css') }}" rel="stylesheet">
{% endblock %}

{% block body %}
<div class="head">
    <img style="padding-top: 10px; padding-left: 10px; height: 35px" src="{{ url_for('static', filename='images/logo-2x.png')}}">
    <p id="logo">GoVl&#234;</p>
    <p ></p>
    <a id="login" href="{{ url_for('login.login_page') }}">Log in or register ↗</a>
</div>
<div class="body">
    <ul>
        <li>All your classes in one place</li>
        <li><button>Get started</button></li>
    </ul>
    <img style="padding-right: 150px; height: 400px;" id="illus" src="{{ url_for('static', filename='images/home-illus.png') }}">

</div>
<div class="block">
    <table>
        <tbody>
            <tr id="column">
                <th>Lorem ipsum</th>
                <th>Nunc efficitur</th>
            </tr>
            <tr id="row">
                <td>dolor sit amet, consectetur 
                    adipiscing elit. Praesent ac tempor arcu, eget pulvinar 
                    velit. Aliquam erat volutpat. Pellentesque nulla mi, 
                    sodales nec purus sit amet, ornare euismod dolor. 
                    Pellentesque lobortis tortor imperdiet, volutpat quam a, 
                    commodo orci. Fusce sit amet tincidunt turpis.
                <td>Lorem id libero interdum 
                    accumsan. Sed ligula arcu, vestibulum vel nulla non, 
                    tempor ultrices lacus. Proin facilisis ex odio. 
                    Maecenas eu turpis non nisl efficitur volutpat ut 
                    eleifend lectus. Nunc vel feugiat nunc, eget rhoncus 
                    risus. Sed at bibendum dolor, eget sodales quam.
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

templates/login.html
{% extends "base-auth.html" %}

{% block title %}
&#8212; Login
{% endblock %}

{% block auth_content %}
<h1 style="margin-bottom: 20px;">Come here often?</h1>
<p>Whether you're new to GoVL&#234; or you already have an account, just click the nifty Sign In button
    below.</p>
<div class="google-signin">
    <div class="g_id_signin" data-type="standard" data-size="large" data-theme="outline"
        data-text="signin_with" data-shape="pill" data-logo_alignment="left">
    </div>
</div>

<p style="font-weight: 700; margin-top: 20px; margin-bottom: 20px; font-size: 14px;">
    Please sign in with your @up.edu.ph Google account.
</p>
<p style="font-size: 14px;">This app is in beta and is therefore limited only to a few students from the
    University of the Philippines Diliman.</p>
{% endblock %}

{% block scripts %}
<script src="https://accounts.google.com/gsi/client" async defer></script>
{% endblock %}